services:
  - type: web
    name: attendance-system
    runtime: docker             # <--- QUAN TRỌNG: Đổi thành docker
    plan: free
    # Không cần buildCommand nữa vì Dockerfile đã lo việc đó
    startCommand: python server.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: MQTT_BROKER
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: 1883
    disk:
      name: attendance-data
      mountPath: /app/classes   # <--- Đổi đường dẫn cho khớp với Docker
      sizeGB: 1